{% set version = "0.1.1" %}

package:
  name: straditize
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/straditize/straditize-{{ version }}.tar.gz
  sha256: 42dac1facd4dabbaaed66e11b942311521260f77c483e559cfe4b7242f0e7e37

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [py == 27]
  entry_points:
    - straditize = straditize.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psyplot-gui >=1.2.2
    - psyplot >=1.2.0
    - netcdf4
    - pyqt >=5
    - scipy
    - numpy >=1.12  # [win]
    - scikit-image
    - openpyxl
    - sphinx !=1.7.5
    - psy-strat

test:
  imports:
    - straditize
    - straditize.widgets
  commands:
    - straditize --help

app:
  entry: straditize
  icon: logo.png
  summary: Stratigraphic Diagram Digitization software
  type: desk

about:
  home: https://github.com/Chilipp/straditize
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: 'Python package for digitizing pollen diagrams'

  description: |
    A software for a semi-automatic digitization of pollen diagrams or
    other types of stratigraphic diagrams using the command line or a
    graphical user interface.
  doc_url: http://straditize.readthedocs.io/
  dev_url: https://github.com/Chilipp/straditize

extra:
  recipe-maintainers:
    - Chilipp
