travis:
  secure:
    BINSTAR_TOKEN: aJky+uwuuxipmQfaM7YEYMltXXX+d4pMoeX1LUsOWn+A8we49DvgjsCU3C/1228AsTAVLWQCMl3/ft76uA9FoSqueuRMHv4O7tDIlVlVuQdKID4IHaQkfMrxTlFUmmZI2qlhA08FICJUPKFMgSPHQvp4EKLRhYwapChOboW02c6TFcLn4Pn4OP/ApkNpewxPTMYa+7oj0XtMhNdVa38/nJvoVSF6pcM876UAbmzu1/x4V/2xp4SLPJkNOZ9F0AkKIHl4qp/5ToiBdzCVWHfBqW+UxbInUTSVp/dKJWjAT7jOVFIx1y7bVFYXDifj/uTmrr1y8SnmI/8zKofE3hr8EKURC7KCE/zAZ8fh33tux96GoeURw8MFnqUhAuv9LnV6wJ+h0E8O6e/s5aFMD6RRZu9rVEYSyn48YKU45SQ8OcO4MpwTPYrNgWnIIfEbcoWngDuDyYSO0qhM31V1Kd04T4r36zdqculWaeuFYpu9DdY21wc1dnS4qx26AeTFeNPFXsNDNS400kTZjojIa5bzegBQnO2DK5GK+WOrAzcPDJ9TT4u4Mvm4ImVxCCB2uIvUydGDS97bkmJqwI1a0che1vSiH/U0bY8VU5yU2fpWwK1rd0Tn27ClKgcQAWiluw7BtpzU4iXas9387VeAhHHJMmSyANrHFnwrjSa586W5vkM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
